### ISSUE TITLE
Enqueue nur beim Laden der Template-Seite

### ISSUE THREAD

**Issue by xwolfde** [SebastianHonert/ili-fau-templates#1]
Bitte lege das enqueue() des CSS und der JS nur wenn die Seite auch tatsächlich geladen wird.

Also innerhalb der 
templates/template-frontpage.php

Register geht schon vorher. Aber enqueue erst dann, wenn man es tatsächlich braucht.

**Comment by SebastianHonert** [comment]
Fixed.
