### ISSUE TITLE
Slider: HTML/tabindex

### ISSUE THREAD

**Issue by xwolfde** [SebastianHonert/ili-fau-templates#11]
Im Slider sind die Elemente mit tabindex=0 versetzt. Warum?

Ggf. hier nochmal schauen und vielleicht auch das umrandende Markup hieran orientieren: https://www.w3.org/WAI/tutorials/carousels/structure/

**Comment by SebastianHonert** [comment]
Kann ich nicht nachvollziehen. Im Quelltext haben alle Elemente tabindex="-1".

**Comment by xwolfde** [comment]
Hm...komisch. Dann war es wohl mein Untersuchen-Werkzeug
