### ISSUE TITLE
enqueue bitte nur wenn gebraucht

### ISSUE THREAD

**Issue by xwolfde** [SebastianHonert/ili-fau-templates#12]
Hallo,

bitte ruf das enqueue() des Frontends nur dann auf, wenn die Seite tatsächlich genutzt wird. Ansonsten wird das CSS und das JS auf jeder Seite eingebunden, auch wenn diese gar keine Landingpage sind. 

Das register() geschieht natürlich beim Laden des Plugins. Das Enqueue jedoch erst in der Funktion einbauen, die die Landingpage generiert (also hier: https://github.com/SebastianHonert/ili-fau-templates/blob/master/ILI/FAUTemplates/templates/template-landing-page.php)

**Comment by SebastianHonert** [comment]
CSS/JS werden per Conditional nur eingebunden, wenn die Seite das Template Landing Page verwendet oder der Shortcode für die Boxen auf der Seite verwendet wird. Im zweiten Fall wird auch nur das CSS/JS für das Plugin geladen, nicht das für den Slick Slider.
