### ISSUE TITLE
Bitte gegen Beta testen

### ISSUE THREAD

**Issue by xwolfde** [SebastianHonert/ili-fau-templates#14]
Hallo,

bitte teste das Plugin auch gegen die neue Beta Version vom Thema:  https://github.com/RRZE-Webteam/FAU-Einrichtungen/tree/beta
Es gab da eine große Zahl an WCAG Bugfixes.

Ciao,
 Wolfgang

**Comment by SebastianHonert** [comment]
Lokal getestet: keine Warnungen/Fehler.
