### ISSUE TITLE
Warnings und Errors bei Nutzung

### ISSUE THREAD

**Issue by xwolfde** [SebastianHonert/ili-fau-templates#15]
Bei Erstinstallation, ohne jegliche Änderung erscheint im Head eine Liste an Warnings:

```html
<br />
| <b>Warning</b>:  Cannot assign an empty string to a string offset in <b>/var/www/vhosts/wordpress/websource/wp-includes/class.wp-scripts.php</b> on line <b>426</b><br />
| <br />
 <b>Warning</b>:  Cannot assign an empty string to a string offset in <b>/var/www/vhosts/wordpress/websource/wp-includes/class.wp-scripts.php</b> on line <b>426</b><br />
  <br />
  <b>Warning</b>:  Cannot assign an empty string to a string offset in <b>/var/www/vhosts/wordpress/websource/wp-includes/class.wp-scripts.php</b> on line <b>426</b><br />
  <br />
  <b>Warning</b>:  Cannot assign an empty string to a string offset in <b>/var/www/vhosts/wordpress/websource/wp-includes/class.wp-scripts.php</b> on line <b>426</b><br />

```

**Comment by xwolfde** [comment]
Und im Contentteil:

```

<!-- Template Part "Topic Boxes" -->

  <section id="ilifautpl-topic-boxes" aria-label="">
  <br />
  <b>Warning</b>:  implode(): Invalid arguments passed in <b>/var/www/vhosts/wordpress/websource/wp-content/plugins/ili-fau-templates/ILI/FAUTemplates/templates/template-parts/template-topic-boxes.php</b> on line <b>7</b><br />
  </section>
  <!-- End Template Part "Topic Boxes" -->
```

**Comment by xwolfde** [comment]
Der Hero-teil scheint auch Problembehaftet:
```

<!-- Template Part "Slider" -->

   <section id="ilifautpl-hero" aria-label="">
   <div class="ilifautpl-hero-inner">
   <style>#ilifautpl-hero::after { transform: none }</style>        </div>
   </section>
   <!-- End Template Part "Slider" -->


```

**Comment by xwolfde** [comment]
Im Backend unter Werkzeuge erscheint diese Warning:

```Notice: Undefined property: ILI\FAUTemplates\Settings::$admin_settings_pageates_field_1 in /var/www/vhosts/wordpress/websource/wp-content/plugins/ili-fau-templates/ILI/FAUTemplates/Settings.php on line 135
```
![2018-10-05-14-46-test8 tindu rrze uni-erlangen de](https://user-images.githubusercontent.com/1070669/46536060-933dd300-c8ad-11e8-8af4-b606097ba839.png)

**Comment by SebastianHonert** [comment]
Für 1. und 2. habe ich einen Fix commited. Bitte testen.

2. Was genau meinst Du mit "problembehaftet"?

3. Ist in Arbeit (admin_settings_pageates_field_1) ist wahrscheinlich Relikt aus dem Plugin-Template, außerdem falsch geschrieben.

**Comment by xwolfde** [comment]
Naja, wenn noch keine Slides definiert wurden, müsste dies erkannt werden; Und so dann eben die leeren Sections noch gar nicht erstellt werden.
Ich teste mal weiter.

**Comment by xwolfde** [comment]
Ok, hab zwei Slides erstellt. Erhalte aber noch die Warning:
Warning: implode(): Invalid arguments passed in /var/www/vhosts/wordpress/websource/wp-content/plugins/ili-fau-templates/ILI/FAUTemplates/templates/template-parts/template-topic-boxes.php on line 7

**Comment by xwolfde** [comment]
Ok, ich muss die eine definierte Box zuordnen um die Warning wegzumachen.

Unschön. Auch hier wäre ein Fallback, der keine Warning auf der produktiven Website meldet,  sinnvoll.

**Comment by SebastianHonert** [comment]
Ich habe einen weiteren Fix committed, der erste war offensichtlich ein Schnellschuss. Die Topic Boxes haben übrigens mit den Slides nichts zu tun.

**Comment by SebastianHonert** [comment]
Fixed: "Notice: Undefined property" in Settings.
