### ISSUE TITLE
Was bedeutet dies?

### ISSUE THREAD

**Issue by xwolfde** [SebastianHonert/ili-fau-templates#18]
"Themenboxen müssen mit einer gültigen Post-ID verknüpft sein."

Wieso? Und was bedeutet dies?

**Comment by xwolfde** [comment]
Ich hab jetzt mal zwei Themenboxen erstellt, die auf eine Post-ID verweisen.

Jetzt erhalte ich dennoch:

"Warning: implode(): Invalid arguments passed in /var/www/vhosts/wordpress/websource/wp-content/plugins/ili-fau-templates/ILI/FAUTemplates/templates/template-parts/template-topic-boxes.php on line 7"#


Aber wieso überhaupt eine Post-Id?  
Die Landing-Oages sind Pages und keine Pages.
Die verweisenden Boxen haben irgendeinen Inhalt.  Welche Boxen verwendet werden, wird doch in der Metabox bei der Seite angegeben. Wozu soll diese Id gut sein?

**Comment by SebastianHonert** [comment]
"Post-ID" habe ich ersetzt durch "Verknüpfter Inhalt (ID)". Die Box muss auf einen vorhandenen Inhalt verweisen, sonst wird die ID nicht gespeichert. Die anderen Warnungen sehe ich mir an, das sind alles Kleinigkeiten.

**Comment by xwolfde** [comment]
Auf was für ein Inhalt denn? Ich versteh es nicht... Und wenn ich es nicht verstehe, dann wird die Webredaktion erst recht planlos sein.
Kannst du mal ein Screenshot von einer Konfig bei dir machen?

**Comment by SebastianHonert** [comment]
Wohin verlinkt eine Themenbox?

**Comment by xwolfde** [comment]
Ich hab aber die ID eines Posts genommen und es hat nichts bewirkt... Die Box wird nicht angezeigt

**Comment by SebastianHonert** [comment]
Ich nehme an, Du willst die Box über das Seiten-Template anzeigen und nicht per Shortcode. Hast Du die Box der Seite hinzugefügt?

<img width="1012" alt="bildschirmfoto 2018-10-05 um 17 11 57" src="https://user-images.githubusercontent.com/7110206/46543862-43b5d200-c8c2-11e8-9dfb-fdf45ce87c40.png">

**Comment by SebastianHonert** [comment]
Es wäre nur eine kleine Änderung im Quelltext, um Shortcodes in den Themenboxen zu ermöglichen. Ich denke aber, dass Shortcodes im Anreißertext nicht wirklich etwas verloren haben.

Bzgl. der Länge des Anreißers: Ich habe dem Shortcode einen Parameter "length" hinzugefügt, mit dem sich die Länge des Textes individuell bestimmen lässt.

Außerdem habe ich eine Plugin-Einstellung für die Default-Länge des Anreißers ergänzt (derzeit mind. 10 Zeichen). Dafür habe ich die Einstellung für das Rollenmodell deaktivert, das hatte sowieso noch keine Funktion. Wird das überhaupt benötigt?

**Comment by SebastianHonert** [comment]
Edit: Parameter geändert in "text_length".

**Comment by xwolfde** [comment]
Thxs. Ich denke, im ersten Beta können wir darauf verzichten. 
Feinschliff können wir später immer noch machen. Dann würde ich solche Parameter irgendwo über den Customizer steuerbar machen. Aber erstmal sollte das bisherige optisch passen.
Ich vermute, wir werden eh noch einiges an Feedback bekommen, so daß wir uns jetzt nicht zu sehr reinstressen sollten.
