### ISSUE TITLE
Tabfocus

### ISSUE THREAD

**Issue by xwolfde** [SebastianHonert/ili-fau-templates#19]
Kann es sein, dass die Pfeile kein Tastatur focus() haben?

**Comment by SebastianHonert** [comment]
Ist korrekt, habe ich im letzten Commit gefixt.

**Comment by xwolfde** [comment]
Hm... naaaja.. Du hast jetzt ein ```<a>``` drumherum gemacht. Der hat aber dann ein leeren Erstreckungstext. Das sieht optisch gut aus, ist aber aus Sicht des W3C/WCAG falsch.  
Korrekt wäre gewesen, wenn du es so gemacht hättest, wie wir es im normalen Slider haben, mit einem Button. Dies macht der SLick eigentlich auch selbstständig. Man muss es nur aktivieren...

Das können/müssen wir aber später noch im Feinschliff machen.

**Comment by SebastianHonert** [comment]
Habe ich im letzten Commit gefixt, die Pfeile sind jetzt Buttons.
