### ISSUE TITLE
<div class="content">

### ISSUE THREAD

**Issue by xwolfde** [SebastianHonert/ili-fau-templates#2]
Bitte bei dem Template das `<div class="content">` nur  einmal für den umrandenenden Contentbereich verwenden, aber nicht für Content-Parts.

Content sollte -wie `<main>` den gesamte Content umschliessen.
Es ist zwar keine id damit verbunden, aber daran hängen andere Teile und Plugins
Bitte lieber eine neue Klasse nennen, wenn nötig.

**Comment by SebastianHonert** [comment]
Fixed.
