### ISSUE TITLE
CSS  

### ISSUE THREAD

**Issue by xwolfde** [SebastianHonert/ili-fau-templates#21]
Das CSS ist in der verwendeten Form nicht komprimiert und dessen Grundlage basiert nicht auf SASS.

Kein Problem für Demo, aber für den dauerhaften Betrieb müssen wir dies anpassen,

**Comment by SebastianHonert** [comment]
Ist angepasst. Neuer Ordner assets/sass kompiliert nach assets/css. Komprimiert das Theme JS Dateien automatisch?

**Comment by xwolfde** [comment]
danke.
JS wird "manuell" von dem jeweiligen Bearbeiter  mit dem eigenen Editorfunktionen gemacht. Dabei aber stets als Dateinamen "$filename.min.js"  für die komprimierte File nehmen und ohne ".min." das original.

Bei SASS passt es so.
