### ISSUE TITLE
Landingpage: besseres Defaultverhalten

### ISSUE THREAD

**Issue by xwolfde** [SebastianHonert/ili-fau-templates#23]
Wenn man eine neue Landingpage anlegt ist noch kein erstes Bild oben angegeben.
Trotzdem wird beim Aufruf schon was gezeigt. Allerdings "nichts":

![image](https://user-images.githubusercontent.com/1070669/46585283-591c2f00-ca6f-11e8-9cb1-f9f511efd7d9.png)

Vorschläge für besseres Defaultverhalten und zur Kompatibilität:

Wenn noch kein erster Slider ausgewählt ist, dann schaue ob nicht stattdessen ein Artikelbild für die Seite definiert ist. Wenn ja, nehme dies.
Wenn weder Slides vorhanden sind, noch ein Artikelbild, dann schaue ob es ein globales Ersatzbild gibt. (Dieses könnte man im Backend über die Settings definieren.)
Wenn kein Bild aus keiner Quelle vorhanden ist, dann zeige eben den Bereich oben gar nicht an/baue dazu kein HTML-Code.

**Comment by SebastianHonert** [comment]
Habe ich wie folgt umgesetzt:

- Wenn kein Slide gewählt, dann Artikelbild
- Wenn kein Artikelbild vorhanden, dann Default-Bild aus Settings
- Zusätzliche Option "Slider anzeigen?" in Template
- Wenn Slider abgeschaltet, wird CSS/JS auch nicht geladen

Es gibt aber noch ein Problem mit den Default-Settings. Die werden zwar nach Plugin-Aktivierung in den Einstellungen angezeigt, müssen aber erst einmal manuell gespeichert werden.

**Comment by xwolfde** [comment]
Jupp.

Allerdings fehlt jetzt bei einem Default-Rücksprung auf das Artikelbild der Seite die Anzeige des Titels (Seitentitel).

**Comment by SebastianHonert** [comment]
Stimmt. Dann wäre es vielleicht auch sinnvoll, eine Checkbox-Option anzubieten, ob der Titel angezeigt werden soll, um auch Landing Pages ohne Titel im Slider anzulegen.

**Comment by SebastianHonert** [comment]
OK, habe ich so umgesetzt.

**Comment by xwolfde** [comment]
Ich glaub das kann zu, oder? (Ich hab Hemmungen , Issues in anderen Repos zu schließen - das steht nur dem jeweiligen Projektowner zu, in diesem Fall dir)
