### ISSUE TITLE
Auswahldialog statt Id-Eingabe

### ISSUE THREAD

**Issue by xwolfde** [SebastianHonert/ili-fau-templates#24]
Für später/nicht dringend:

Bei der Definition der Boxes sollte die EIngabe der ID nach einem Objekt ersetzt werden durch ein WordPress-Modal, welches die vorhandenen Seiten/Posts auswählen/suchen lässt.

**Comment by SebastianHonert** [comment]
Ich habe [Select2](https://select2.org/) hinzugefügt, Inhalte können jetzt per Suchfeld/Dropdown eingefügt werden.

**Comment by xwolfde** [comment]
passt, super
