### ISSUE TITLE
Weiterlesen-Link optional

### ISSUE THREAD

**Issue by xwolfde** [SebastianHonert/ili-fau-templates#25]
Wenn Themenboxen kein Inhalt enthalten (da sie nur aus Titel + Bild bestehen), macht der Weiterlesen-Link kein Sinn:
![image](https://user-images.githubusercontent.com/1070669/46585377-71d91480-ca70-11e8-9616-d96732d82406.png)

Für solche Fälle sollte man bei der Landingpage die Option haben, den Weiterlesen-Link auf diese Seite (für alle Themenboxen dann unabhängig von deren Inhalt) aus bzw. anzuschalten.

**Comment by SebastianHonert** [comment]
Option zur Anzeige des Weiterlesen-links hinzugefügt, zusätzlich Parameter "read_more" für Shortcode "themenbox".

**Comment by xwolfde** [comment]
ok
