### ISSUE TITLE
Copyright-Info?

### ISSUE THREAD

**Issue by xwolfde** [SebastianHonert/ili-fau-templates#26]
Wo ist denn bei den Slides die Copyright-Info?

**Comment by SebastianHonert** [comment]
Habe ich hinzugefügt, wird bei den Slides mit angegeben und falls vorhanden im Slide mit angezeigt.

<img width="1276" alt="bildschirmfoto 2018-10-09 um 14 12 21" src="https://user-images.githubusercontent.com/7110206/46668652-5f282200-cbcd-11e8-8f5f-493dc0839be5.png">

Wie ist denn bei den Themenboxen zu verfahren? Brauchen die auch eine Möglichkeit, Credits anzugeben?

**Comment by SebastianHonert** [comment]
Ich habe die Opacity noch ein wenig erhöht, der Hintergrund ist jetzt fast weiß.

Unter dem Bild wird bei geringeren Bildschirmauflösungen nicht gut funktionieren, weil dort ja die Navigation für die Slides liegen kann. Durch die Einbettung in den Slide wird aus meiner Sicht auch schön ersichtlich, dass das Copyright-Element zu diesem Bild gehört.

Vielleicht warten wir einfach mal ab, was die VP sagen? So oft wird dort sicher auch gar kein geschütztes Bildmaterial auftauchen, oder liege ich da falsch?

**Comment by xwolfde** [comment]
Ja, machen wir so. 
(Bildmaterial: Naja, es sind leider doch oft Stockerbilder dabei oder Bilder, die ein beschränktes Nutzungsrecht haben)

**Comment by SebastianHonert** [comment]
OK, dann warten wir ab. Es muss ja niemand mit dem Kopf darauf gestoßen werden.

Wo wir gerade dabei sind: Was hältst Du denn von dem hover beim Slide-Titel (border-bottom)? Bin mir nicht sicher, ob ich das schick finden soll.

**Comment by xwolfde** [comment]
Ich weiß nicht, den Animation-Effekt finde ich an sich schon gut. Ich finde nur den Abstand des Unterstrich zum Text zu groß.

Hier hatte ich selbst ähnliches mal gemacht: https://www.kreuzfahrten-reisetagebuch.de/ Da bin ich dann am Ende dazu gekommen, lediglich die Schriftfarbe zu ändern.

**Comment by SebastianHonert** [comment]
So ist doch schick: https://sebastianhonert.com/fau/

**Comment by xwolfde** [comment]
jupp
