### ISSUE TITLE
Themenboxen über Shortcode in beliebigen Pages einfügen?

### ISSUE THREAD

**Issue by xwolfde** [SebastianHonert/ili-fau-templates#27]
Wäre es denkbar, die Themenboxen über ein Shortcode derart in beliebigen Pages einzufügen:

[themenboxen id="1,2,3,4"]

zeigt die Themenboxen der Ids 1, 2, 3 und 4 an.

**Comment by SebastianHonert** [comment]
Ja, der Shortcode existiert bereits und wird auch im Template verwendet. Du musst nur den Parameter für die IDs von "id" ändern in "ids".

**Comment by xwolfde** [comment]
Aah, ich hatte sowas im Gefühl.
Könntest du die Shortcodes vielleicht in der README (die gibt es ja noch nicht) auflisten?
Spätestens wenn wir es an die Webredaktion rausgeben, wird die nämlich danach fragen.
