### ISSUE TITLE
Zeichenzähler defekt?

### ISSUE THREAD

**Issue by xwolfde** [SebastianHonert/ili-fau-templates#28]
Also ich hab 500 Zeichen eingestellt in den Settings.

Trotzdem werden selbst Texte, die nur 184 Zeichen lang sind, abgeschnitten: 
![image](https://user-images.githubusercontent.com/1070669/46586125-29265900-ca7a-11e8-8ccb-4f56dfc8950c.png)

**Comment by SebastianHonert** [comment]
Sollte gefixt sein.
