### ISSUE TITLE
Template Inhaltsbereich nutzen

### ISSUE THREAD

**Issue by xwolfde** [SebastianHonert/ili-fau-templates#29]
Bei Templates kann es sinnvoll sein, einen echten eigenen Textinhalt zu setzen, statt gleich die Blogroll.

Daher würde ich vorschlagen, dass nach dem Bereich der Themenboxen und vor der Blogroll der
content()
derjeweiligen Page gezeigt wird.
Dieser ist ja bereits eingebbar gewesen.

**Comment by SebastianHonert** [comment]
Habe ich eingefügt.
