### ISSUE TITLE
Iconbilder?

### ISSUE THREAD

**Issue by xwolfde** [SebastianHonert/ili-fau-templates#3]
Wo braucht man denn die?
ili-fau-templates/tree/master/assets/img

Da wir auf Awesome-Font beruhen, bitte auch die Awesome-Lib verwenden - die haben wir nämlich schon geladen und so gewinnen wir Performance

**Comment by SebastianHonert** [comment]
Da ist derzeit nur das Bild für die Pfeilnavigation drin (846 bytes), das sollte zu verschmerzen sein.

**Comment by SebastianHonert** [comment]
Ich habe mich vorerst am Entwurf von Roland orientiert, da sehen die Pfeile nicht aus wie die Chevrons. Ist natürlich nicht in Stein gemeißelt.

**Comment by xwolfde** [comment]
Bitte die chevrons nutzen- Sonst ists uneinheitlich (es gibt ja nicht nur den Slider) und wir haben 2 Dateien mehr im Ladestack. Die Chevrons kann man ja auch in Höhe und Breite strecken, wenn man will. 
Alternative wäre allenfalls ein SVG-Code. Aber Bilder sind echt 2 Generationen out: Neue Seiten nutzen SVGs, alte/aktuelle Iconsfonts.

**Comment by SebastianHonert** [comment]
Fixed.
