### ISSUE TITLE
Verknüpfter Inhalt: Keine kleinen IDs möglich

### ISSUE THREAD

**Issue by xwolfde** [SebastianHonert/ili-fau-templates#32]
Bei EIngabe der ID bei der Erstellung einer Themenbox werden drei Zeichen verlangt.
Eine ID kleiner 100 kann somit nicht eingegeben werden.

Bitte da nur auf eine Zahl prüfen, aber nicht auf Stringlen.

**Comment by xwolfde** [comment]
Ah, bitte diesen Issue invalid löschen. Hab jetzt erst erkannt, dass dort Text für den Titel einzugeben ist,.
Dabnn aber bitte den Titel der Metabox ändern: Da steht dass man da eine "ID" eingibt.

**Comment by SebastianHonert** [comment]
Fixed.
