### ISSUE TITLE
Anzahl der Themenboxen?

### ISSUE THREAD

**Issue by xwolfde** [SebastianHonert/ili-fau-templates#33]
Ich hab bei einer Landingpage 4 Slides definiert und 5 Themenboxen darunter.

Es werden aber nur 4 Themenboxen gezeigt.
https://www.beta.wordpress.rrze.fau.de/templates/landingpages-pero/

**Comment by SebastianHonert** [comment]
Die Themenbox war mit einem Inhalt namens "Studium" verknüpft, den es nicht gibt. Habe ich auch "Studienangebot" geändert, damit funktioniert es.
