### ISSUE TITLE
Template klingt sich in Suchergebnisse ein, zerstört die Ausgabe

### ISSUE THREAD

**Issue by xwolfde** [SebastianHonert/ili-fau-templates#34]
Dies ist ein gravierendes Problem:

Die Siteinterne Suche durchsucht bekanntlich posts und pages.
Bei Auffinden eines Treffers welches ein ILI Template ist, wird die Suchergebnisseite komplett kaputt gemacht indem der Content  fast den gesamten Inhalt von Seiten wiedergibt,d ie irgendwas mit dem Template zu tun haben.

Nachstellbar:  Suche nach irgendwas ausführen.

**Comment by SebastianHonert** [comment]
Das Problem war, dass das Landing-Page-Template das Template für die Suche überschrieben hat. Sollte gefixt sein, bitte einmal überprüfen.
