### ISSUE TITLE
THemenbox deaktiviert sich selbst bei Bildänderung

### ISSUE THREAD

**Issue by xwolfde** [SebastianHonert/ili-fau-templates#35]
Wenn man bei einer gesetzten und in einer Landingpage aktivierten Themenbox das Beitragsbild  ändert, wird die Themenbox für die Landingpage deaktiviert.

**Comment by xwolfde** [comment]
Ergänzung: Der "Verknüpfte Inhalt" wird dann deaktiviert und setzt sich zurück auf nichts.

**Comment by xwolfde** [comment]
Passiert auch, wenn ich andere Teile des Posts im Editor ändere.

**Comment by SebastianHonert** [comment]
Gefixt.

Außerdem ein neues Feld hinzugefügt: Target-URL (falls Archivseiten oder externe Links in einer Themenbox verknüpft werden sollen).

**Comment by xwolfde** [comment]
thxs, habs übernommen.


Übrigens könntest du mal deine Versionsnummern updaten  - Die steht stabil auf der 0.0.1 :)
Hier ein Verfahren, wie wir da vorgehen: https://www.beta.wordpress.rrze.fau.de/entwicklung/git/versionsnummern/
