### ISSUE TITLE
Bitte GET-Werte sanitizen

### ISSUE THREAD

**Issue by xwolfde** [SebastianHonert/ili-fau-templates#37]
Mir scheint, hier fehlt das Sanitizing von  $_GET['q'].

```
function ilifautpl_get_posts_ajax_callback()
{
    $return = array();
     
    $search_results = new \WP_Query( array( 
		's' => $_GET['q'],
        'post_type' => array('post', 'page'),
		'post_status' => 'publish',
		'posts_per_page' => 50,
	) );
    
	...
}

```

(ili-fau-templates-master.php)

**Comment by SebastianHonert** [comment]
Um das Sanitizing kümmert sich ziemlich sicher die Klasse WP_Query.

[https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-query.php](https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-query.php)

Habe trotzdem ein `sanitize_text_field()` hinzugefügt, schadet ja auch nicht.

**Comment by xwolfde** [comment]
Ja, haben wir im Team genauso gesehen.
