### ISSUE TITLE
Template Section title 

### ISSUE THREAD

**Issue by xwolfde** [SebastianHonert/ili-fau-templates#38]
Gemäß WCAG 2.1 AA brauchen Sections einen ARIA Bezeichnung. DIe leere AUszeichnung reicht nicht.
In der darauf folgenden h2 ist aber ein Titel:

```
echo '<section id="ilifautpl-hero" class="' . $ilifautpl_slider_classes . '" aria-label="">';
echo '<div class="ilifautpl-hero-inner">';
echo '<h2 class="screen-reader-text">' . __('Slider', 'ilifautpl') . '</h2>';
```

Ändern auf:

aria-label="'__('Slider', 'ilifautpl').''"

und die h2 wegmachen.

**Comment by SebastianHonert** [comment]
Erledigt.
