### ISSUE TITLE
Überschriftenhierachie falsch

### ISSUE THREAD

**Issue by xwolfde** [SebastianHonert/ili-fau-templates#6]
Bitte die Überschriftenhierachie und den Gebrauch der h3 als Text korrgieren, da ist so nicht konform zur WCAG ist:

![landingpage-fluchtlinie-headline-hierachie](https://user-images.githubusercontent.com/1070669/44869716-94685880-ac8e-11e8-9617-7bd7ebac492b.jpg)

Über dem Slider bitte eine unsichtbare h2 machen als Overebene mit einem Titel wie es bei dem fau theme im slider bereits vorhanden ist:

```<h2 class="screen-reader-text"><?php echo __('Slider','fau'); ?></h2>```

Der Titel muss dann statt einer `<h2>` eine `<h3>` sein.
Die jetzige  `<h3>`  wird zu einem `<p>` .
Gestaltung in CSS.

**Comment by SebastianHonert** [comment]
Fixed.
