### ISSUE TITLE
Kasten der Landingpage - "Weiterlesen"

### ISSUE THREAD

**Issue by xwolfde** [SebastianHonert/ili-fau-templates#8]
Ich finde die Variante ein klaren Link "Weiterlesen" zu haben, ebenfalls besser als das was derzeit auf der FAU Seite ist (dort sind  ein bzw beim hover zwei Pfeile nach rechts und "Weiterlesen" ist nur für den Screenreader). Bei dir auch weiter unten bei der Blogroll mit "Hallo Welt".
![landingpage-kasten](https://user-images.githubusercontent.com/1070669/44870190-ca5a0c80-ac8f-11e8-96ec-4cc85811c49f.png)

Aber es sollte dennoch einheitlich sein.

Vorschlag an der Stelle: "Weiterlesen" als Link wird auch bei der Default Blogroll gemacht. Dafür bräuchte ich aber einen Fürsprecher.

**Comment by SebastianHonert** [comment]
Die Rolle des Fürsprechers übernehme ich gerne. Text ist korrigiert.
